/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package gui.mini.compiler;

import gui.mini.compiler.UserInterface.MainUI;

public class App {
    public static void main(String[] args) {
        MainUI mainUI = new MainUI();
        System.out.println("Ewan");
    }
}
