/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package gui.mini.compiler;

import gui.mini.compiler.Compiler.*;

import java.util.List;

public class App {
    public static void main(String[] args) {
        // INT, STRING_TYPE, CHAR, DOUBLE, FLOAT, BOOLEAN,
        String input = "int x = 0; \n" +
                "char gender = 'M';" +
                "String name = \"Renard\";" +
                "double y = 1.03;\n" +
                "float xy = 1.03f;\n" +
                "boolean istrue = true;\n";
        System.out.println(input);
        Lexer lexer = new Lexer(input);
        List<Token> token = lexer.getTokens();

        for (Token tokens : token) {
            System.out.println(tokens.toString());

        }

        Parser parser = new Parser(token);

        parser.initParser();
    }

}
